"""empty message

Revision ID: 2e7db2e64e5f
Revises: 8e82aa22621e
Create Date: 2018-05-04 22:27:06.112000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7db2e64e5f'
down_revision = '8e82aa22621e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('subtitle', sa.Text(), nullable=True))
    op.drop_column('feeds', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('feeds', 'subtitle')
    # ### end Alembic commands ###
