"""empty message

Revision ID: 8e82aa22621e
Revises: 30514497efa1
Create Date: 2018-05-04 22:25:28.852216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e82aa22621e'
down_revision = '30514497efa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'title')
    op.drop_column('feeds', 'description')
    # ### end Alembic commands ###
